### ISSUE TITLE
ENV config vars are ignored

### ISSUE THREAD

**Issue by chiefy** [chiefy/vaulted#71]
```
var Vaulted = require('vaulted');
console.log('VAULT_HOST = '+ process.env.VAULT_HOST);

var vault = new Vaulted({
    secret_shares: 1,
    secret_threshold: 1,
    debug: true
});
vault
    .prepare(token)
    .bind(vault)
    .then(function() {
        console.log(this);
    });
```

```
> node lib/index.js

VAULT_HOST = 192.168.99.100
{ request:
   { debugId: 1,
     uri: 'https://127.0.0.1:8200/v1/sys/init',
     method: 'GET',
     headers: { host: '127.0.0.1:8200', accept: 'application/json' } } }
Unhandled rejection RequestError: Error: connect ECONNREFUSED 127.0.0.1:8200
    at new RequestError (/Users/ext.cnajewicz/GitHub/vaulted/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/Users/ext.cnajewicz/GitHub/vaulted/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/Users/ext.cnajewicz/GitHub/vaulted/node_modules/request/request.js:198:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/Users/ext.cnajewicz/GitHub/vaulted/node_modules/request/request.js:820:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

**Comment by kenjones-cisco** [comment]
Yep, I realized that the day after the last set of updates. So I've been working on something to resolve this moving forward.

**Comment by kenjones-cisco** [comment]
Try out branch `chore/config`

Let me know if you have any issues.
