### ISSUE TITLE
Feature: Upgrade to support Vault 0.5.x

### ISSUE THREAD

**Issue by kenjones-cisco** [chiefy/vaulted#76]
Vault 0.5.0 was released today (https://www.hashicorp.com/blog/vault-0.5.html)
- [x] Apply upgrades to [authstore](https://github.com/kenjones-cisco/authstore) project to provide Vault 0.5.0 for testing
- [x] Handle nonces for rekey
- [ ] policy to capabilities conversion
- [ ] API listing (as needed)
- [ ] Unseal key backup option (pgp required)
- [ ] Root Token Generation
- [ ] Lease duration

Other changes could be required depending on further analysis of the release.

**Comment by chiefy** [comment]
:+1: just saw this

**Comment by kenjones-cisco** [comment]
After updating the Vault image to 0.5.0 and running the code as it currently stands, the following is the errors: (only 6, so pretty good shape overall)

```
  1) auth/tokens #revokeTokenPrefix should resolve after token prefix revoked:
     AssertionError: expected promise to be fulfilled but it was rejected with { Object (name, statusCode, ...) }


  2) pki #issueCertCredentials should resolve when all required and valid inputs provided:
     AssertionError: expected { Object (certificate, issuing_ca, ...) } to have a property 'serial_number'
      at tests/backends/pki.js:593:31
      at tryCatcher (node_modules/bluebird/js/release/util.js:11:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:489:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:546:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:591:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:674:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:125:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:135:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:16:14)

  3) pki #getCertSerial should resolve when all required and valid inputs provided:
     Error: Endpoint requires an id.
      at Endpoint.validateId (lib/endpoint.js:9:1974)
      at Hooks.execPre (lib/hooks.js:9:755)
      at Endpoint.impl (lib/endpoint.js:9:8232)
      at Endpoint.wrapper [as get] (node_modules/lodash/index.js:3592:19)
      at Vaulted.getCertSerial (lib/backends/pki.js:9:4727)
      at Vaulted.tryCatcher (node_modules/bluebird/js/release/util.js:11:23)
      at Vaulted.getCertSerial (node_modules/bluebird/js/release/method.js:15:34)
      at Context.<anonymous> (tests/backends/pki.js:628:22)

  4) pki #revokeCertCredentials should resolve when all required and valid inputs provided:
     Error: Missing required input serial_number
      at lib/endpoint.js:9:3169
      at arrayEach (node_modules/lodash/index.js:1289:13)
      at Function.<anonymous> (node_modules/lodash/index.js:3345:13)
      at Endpoint.validateBody (lib/endpoint.js:9:2594)
      at Hooks.execPre (lib/hooks.js:9:755)
      at Endpoint.impl (lib/endpoint.js:9:8232)
      at Endpoint.wrapper [as post] (node_modules/lodash/index.js:3592:19)
      at Vaulted.revokeCertCredentials (lib/backends/pki.js:9:9788)
      at Vaulted.tryCatcher (node_modules/bluebird/js/release/util.js:11:23)
      at Vaulted.revokeCertCredentials (node_modules/bluebird/js/release/method.js:15:34)
      at Context.<anonymous> (tests/backends/pki.js:688:22)

  5) keys #updateRekey should resolve with instance of binded Vault - complete false:
     StatusCodeError: 400 - [object Object]
      at new StatusCodeError (node_modules/request-promise/lib/errors.js:26:15)
      at Request.RP$callback [as _callback] (node_modules/request-promise/lib/rp.js:68:32)
      at Request.self.callback (node_modules/request-promise/node_modules/request/request.js:198:22)
      at Request.<anonymous> (node_modules/request-promise/node_modules/request/request.js:1035:10)
      at IncomingMessage.<anonymous> (node_modules/request-promise/node_modules/request/request.js:962:12)
      at endReadableNT (_stream_readable.js:905:12)

  6) keys #updateRekey should resolve with instance of binded Vault - complete true:
     StatusCodeError: 400 - [object Object]
      at new StatusCodeError (node_modules/request-promise/lib/errors.js:26:15)
      at Request.RP$callback [as _callback] (node_modules/request-promise/lib/rp.js:68:32)
      at Request.self.callback (node_modules/request-promise/node_modules/request/request.js:198:22)
      at Request.<anonymous> (node_modules/request-promise/node_modules/request/request.js:1035:10)
      at IncomingMessage.<anonymous> (node_modules/request-promise/node_modules/request/request.js:962:12)
      at endReadableNT (_stream_readable.js:905:12)
```

**Comment by chiefy** [comment]
@kenjones-cisco have you tried running w/latest vault?

**Comment by kenjones-cisco** [comment]
not yet

**Comment by chiefy** [comment]
FWIW - unit tests have been fixed in version `3.0.1`

**Comment by jmls** [comment]
so, does this mean that vaulted supports 0.5.0 ? ;)

**Comment by chiefy** [comment]
@jmls yes, but I need to create a release. Will do it ASAP this weekend.

**Comment by jmls** [comment]
heh. remember that 0.6.0 is at rc-1 stage :)

**Comment by chiefy** [comment]
@jmls PRs are always welcome 😄

**Comment by chiefy** [comment]
@jmls just pushed a new release to `npm` that supports Vault 0.5.x and 0.6, this thread will continue to track feature parity, I will change the title.

**Comment by jmls** [comment]
you da man ;) thanks

**Comment by jmls** [comment]
if 0.6 is supported, does that mean response wrapping is supported ? ;)
